force-app/main/default/objects/Generic_Custom_JSON__c/Generic_Custom_JSON__c.object-meta.xml
<CustomObject>
    <label>Generic Custom Parameter</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Generic Custom Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/custom_parent__c.field-meta.xml
<CustomField>
    <fullName>custom_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generic Custom Parameter Parent</label>
    <referenceTo>Generic_Custom_JSON__c</referenceTo>
    <relationshipLabel>Generic Custom</relationshipLabel>
    <relationshipName>Generic_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWCController.cls
public with sharing class LWCController {
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactList(Integer count){
        return [SELECT Id, Name, Title, Phone, Email, Picture__c FROM Contact LIMIT :count];
    }

    @AuraEnabled(cacheable=true)
    public static List<Generic_Custom_JSON__c> getRecordList(String queryString){
        String identifier = 'testIden';
        queryString = 'Select Id, custom_parent__c, custom_parent__r.Name, Value__c, name, Identifier__c From Generic_Custom_JSON__c Where Identifier__c = :identifier';
        return Database.query(queryString);
    }
}