force-app/main/default/objects/Generic_Custom_JSON__c/Generic_Custom_JSON__c.object-meta.xml
<CustomObject>
    <label>Generic Custom Parameter</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Generic Custom Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/custom_parent__c.field-meta.xml
<CustomField>
    <fullName>custom_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generic Custom Parameter Parent</label>
    <referenceTo>Generic_Custom_JSON__c</referenceTo>
    <relationshipLabel>Generic Custom</relationshipLabel>
    <relationshipName>Generic_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CloneSObjectDAG.cls
public without sharing class CloneSObjectDAG {
    public static void demoMethod(Id attachmentRecord) {

        // attachmentRecord = '0017F00002l6spTQAQ';

        List<WrapperClass> listOfWrapperClasses = new List<WrapperClass>();
        List<Account> accList = [
            SELECT Id, name, description 
            FROM Account 
            WHERE id = '0017F00002l6spTQAQ'
        ];
        WrapperClass accountRecords = new WrapperClass(
            accList,
            null,
            'Account',
            false,
            null
        );
        listOfWrapperClasses.add(accountRecords);

        WrapperClass contactRecords = new WrapperClass(
            [
                SELECT Id, AccountId, account.name,account.description, lastname 
                FROM contact 
                WHERE Accountid = :accList[0].Id
            ],
            new Set<String> {
                'AccountId'
            },
            'Contact',
            false,
            null
        );
        listOfWrapperClasses.add(contactRecords);

        WrapperClass opportunityRecords = new WrapperClass(
            [
                SELECT Id, name, Amount, CloseDate, AccountId, StageName 
                FROM Opportunity 
                WHERE Accountid = :accList[0].Id
            ],
            new Set<String> {
                'AccountId'
            },
            'Opportunity',
            false,
            null
        );
        listOfWrapperClasses.add(opportunityRecords);

        WrapperClass genericRecords = new WrapperClass(
            [
                SELECT Id, Name, Value__c, custom_parent__c, Opportuntiy__c, Identifier__c 
                FROM Generic_Custom_JSON__c
                WHERE Identifier__c = 'testIden'
            ],
            new Set<String> {
                'Opportuntiy__c',
                'custom_parent__c'
            },
            'Generic_Custom_JSON__c',
            true,
            'custom_parent__c'
        );
        listOfWrapperClasses.add(genericRecords);


        CloneSObjectDAGUtility.main(listOfWrapperClasses, attachmentRecord);

    }

    public class WrapperClass {
        public List<sObject> records;
        public String sObjectName;
        public Set<String> fieldsToRef;
        public Boolean hasSelfRelationship;
        public String ifSelfRefThenFieldName;

        public WrapperClass(List<sObject> records,  Set<String> fieldsToRef, String sObjectName,Boolean hasSelfRelationship, String ifSelfRefThenFieldName) {
            this.records = records;
            this.sObjectName = sObjectName;
            this.fieldsToRef = fieldsToRef;
            this.hasSelfRelationship = hasSelfRelationship;
            this.ifSelfRefThenFieldName = ifSelfRefThenFieldName;
        }
    }

    
}