force-app/main/default/objects/Generic_Custom_JSON__c/Generic_Custom_JSON__c.object-meta.xml
<CustomObject>
    <label>Generic Custom Parameter</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Generic Custom Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/custom_parent__c.field-meta.xml
<CustomField>
    <fullName>custom_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generic Custom Parameter Parent</label>
    <referenceTo>Generic_Custom_JSON__c</referenceTo>
    <relationshipLabel>Generic Custom</relationshipLabel>
    <relationshipName>Generic_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JSONGeneratorForCLITest.cls
@isTest
public class JSONGeneratorForCLITest {
    public JSONGeneratorForCLITest() {}

    @testSetup
    private static void testSetup() {
        // List<Generic_Custom_JSON__c> recordList = new List<Generic_Custom_JSON__c>();
        Generic_Custom_JSON__c parent = new Generic_Custom_JSON__c(
            // Name = 'Parent',
            Identifier__c = 'generic'
        );
        insert parent;
        Generic_Custom_JSON__c child = new Generic_Custom_JSON__c(
            // Name = 'Child',
            Identifier__c = 'child',
            custom_parent__c = parent.Id
        );
        insert child;
    }

    @isTest
    private static void genericTest() {
        Generic_Custom_JSON__c parentRecord = [
            SELECT Id 
            FROM Generic_Custom_JSON__c 
            WHERE Identifier__c = 'generic' 
            LIMIT 1
        ];
        // JSONGeneratorForCLI.recordId = parentRecord.Id;
        JSONGeneratorForCLI.demo(parentRecord.Id);
    }
}