force-app/main/default/objects/Generic_Custom_JSON__c/Generic_Custom_JSON__c.object-meta.xml
<CustomObject>
    <label>Generic Custom Parameter</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Generic Custom Parameter</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/custom_parent__c.field-meta.xml
<CustomField>
    <fullName>custom_parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Generic Custom Parameter Parent</label>
    <referenceTo>Generic_Custom_JSON__c</referenceTo>
    <relationshipLabel>Generic Custom</relationshipLabel>
    <relationshipName>Generic_Custom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Generic_Custom_JSON__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TreeComponentController.cls
public class TreeComponentController {
	
    @auraEnabled
    public static List<Generic_Custom_JSON__c> getCustomJson(String identifier) {
        List<Generic_Custom_JSON__c> genericList = new List<Generic_Custom_JSON__c>();
        genericList = [
            Select Id, Name, Custom_Parent__c, Value__c 
            from Generic_Custom_JSON__c 
            Where identifier__c = :identifier 
            Limit 200
        ];
        return genericList;
    }
}