force-app/main/default/objects/Batch_Progress__e/Batch_Progress__e.object-meta.xml
<CustomObject>
    <label>Batch Progress</label>
    <pluralLabel>Batch Progress</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Progress__e/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Progress__e/fields/Class_name__c.field-meta.xml
<CustomField>
    <fullName>Class_name__c</fullName>
    <label>Class name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Progress__e/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Progress__e/fields/DML_type__c.field-meta.xml
<CustomField>
    <fullName>DML_type__c</fullName>
    <label>DML type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Progress__e/fields/isSuccess__c.field-meta.xml
<CustomField>
    <fullName>isSuccess__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isSuccess</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Progress__e/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <description>Sobject name whose record is processed in batch</description>
    <label>ObjectApiName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProcessAccountsBatch.cls
public class ProcessAccountsBatch implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            'SELECT ID, Name, NumberOfEmployees, BillingCity, BillingState, ' +
            'BillingPostalCode FROM Account'
        );
    }

    private static Integer incrementByOne(Integer count) {
        return (count == null) ? 1 : count++;
    }
    public void execute(Database.BatchableContext bc, List<Account> accountRecords){
        // process each batch of records
        for(Account acc : accountRecords) {
            acc.NumberOfEmployees = incrementByOne(acc.NumberOfEmployees);
        }

        try {
            update accountRecords;

            Batch_Progress__e bpEvent = new Batch_Progress__e();

            AsyncApexJob job = [
                SELECT Id, Status, NumberOfErrors,
                JobItemsProcessed,
                TotalJobItems
                FROM AsyncApexJob
                WHERE Id = :bc.getJobId()
            ];

            bpEvent.Batch_Id__c = bc.getJobId();
            bpEvent.Class_name__c = 'ProcessAccountsBatch';
            bpEvent.Count__c = Integer.valueOf(job.JobItemsProcessed);
            bpEvent.DML_type__c = 'Update';
            bpEvent.isSuccess__c = true;
            bpEvent.ObjectApiName__c = 'Account';

            Database.SaveResult results = EventBus.publish(bpEvent);
            
            if (results.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : results.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }
            
        } catch(Exception e) {
            system.debug(e);
        }
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}