force-app/main/default/objects/CustomObj__c/CustomObj__c.object-meta.xml
<CustomObject>
    <label>CustomObj</label>
    <nameField>
        <label>CustomObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CustomObj</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomObj__c/fields/Clarification__c.field-meta.xml
<CustomField>
    <fullName>Clarification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clarification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomObj__c/fields/CustomObj__c.field-meta.xml
<CustomField>
    <fullName>CustomObj__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>my child</description>
    <label>CustomObj</label>
    <referenceTo>CustomObj__c</referenceTo>
    <relationshipLabel>CustomObj</relationshipLabel>
    <relationshipName>CustomObj</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomObj__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CustomObj</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomObjManager.cls
@RestResource(urlMapping='/CustomObj/*')
global with sharing class CustomObjManager {
    @HttpGet
    global static CustomObj__c getObjById() {
        RestRequest request = RestContext.request;
        // grab the caseId from the end of the URL
        String MyId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        CustomObj__c result =  [SELECT Clarification__c,Name,Email__c,User__c
                        FROM CustomObj__c
                        WHERE Id = :MyId];
        return result;
    }
    @HttpPost
    global static ID createCase(String name, String Email,
        String User, Boolean clarification) {
        CustomObj__c thisCase = new CustomObj__c(
            Name=name,
            Clarification__c=clarification);
        insert thisCase;
        return thisCase.Id;
    }           
}