force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Childs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child__c/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <inlineHelpText>select parent</inlineHelpText>
    <label>Mother</label>
    <referenceTo>Mother__c</referenceTo>
    <relationshipLabel>Childs</relationshipLabel>
    <relationshipName>Childs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mother__c/Mother__c.object-meta.xml
<CustomObject>
    <label>Mother</label>
    <nameField>
        <label>Mother Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mothers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mother__c/fields/Daughters__c.field-meta.xml
<CustomField>
    <fullName>Daughters__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daughters</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mother__c/fields/Sons__c.field-meta.xml
<CustomField>
    <fullName>Sons__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/motherServiceLayer.cls
public with sharing class motherServiceLayer {
    public motherServiceLayer() {

    }

    public class MSLException extends exception {
    }

    public static void updateMotherCount(Set<Id> motherIdSet) {

        if(motherIdSet.isEmpty()) return;

        Map<Id, Mother__c> motherMap = new Map<Id, Mother__c>();
        
        for(Child__c child : [SELECT Id, Gender__c, Mother__c FROM Child__c WHERE Mother__c in :motherIdSet]) {
            if(!motherMap.containsKey(child.Mother__c)) {
                motherMap.put(child.Mother__c, new Mother__c(Id=child.Mother__c, Sons__c = 0, Daughters__c = 0));
            }
            Mother__c temp = motherMap.get(child.Mother__c);
            System.debug('temp mother' + temp);
            if (child.Gender__c == 'Male') temp.Sons__c += 1;
            if (child.Gender__c == 'Female') temp.Daughters__c += 1;
            motherMap.put(child.Mother__c, temp);
        }

        safelySave(motherMap.values());
        return;
    }

    @testVisible
    private static void safelySave(List<Mother__c> motherRecords) {
        try {
            System.SObjectAccessDecision decision = Security.stripInaccessible(
                AccessType.UPDATABLE,
                motherRecords
            );
            update decision.getRecords();
        } catch (DMLException dmle) {
            System.debug(
                LoggingLevel.INFO,
                'Hey, a DML error occurred while updating.'
            );
            throw new MSLException(dmle.getMessage());
        } catch (System.NoAccessException nae) {
            throw new MSLException(nae.getMessage());
        }
    }
}