force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Childs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Child__c/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <inlineHelpText>select parent</inlineHelpText>
    <label>Mother</label>
    <referenceTo>Mother__c</referenceTo>
    <relationshipLabel>Childs</relationshipLabel>
    <relationshipName>Childs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mother__c/Mother__c.object-meta.xml
<CustomObject>
    <label>Mother</label>
    <nameField>
        <label>Mother Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mothers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/childTriggerHandler.cls
public class childTriggerHandler extends triggerHandler{
    private List<child__c> triggerNew;
    private List<child__c> triggerOld;
    private Map<Id, child__c> triggerMapNew;
    private Map<Id, child__c> triggerMapOld;
    /**
     * @description Constructor that sets class variables based on Trigger
     * context vars
     */
    public ChildTriggerHandler() {
        this.triggerOld = (List<child__c>) Trigger.old;
        this.triggerNew = (List<child__c>) Trigger.new;
        this.triggerMapNew = (Map<Id, child__c>) Trigger.newMap;
        this.triggerMapOld = (Map<Id, child__c>) Trigger.oldMap;
    }

    /**
     * @description Custom exception class
     */
    public class ChildTriggerHandlerException extends Exception {
    }

    public override void afterInsert() {
        this.updateMotherData(this.triggerNew);
    }

    public override void afterUpdate(){
        this.checkIfMotherDataIsToBeUpdated();
    }





    private void checkIfMotherDataIsToBeUpdated() {
        Set<Id> motherIdSet = new Set<Id>();
        for(child__c child : this.triggerNew) {
            if(
                child.Mother__c != this.triggerMapOld.get(child.Id).Mother__c
                || child.Gender__c != this.triggerMapOld.get(child.Id).Gender__c
            ) {
                motherIdSet.add(child.Mother__c);
                motherIdSet.add(this.triggerMapOld.get(child.Id).Mother__c);
            }
        }
        this.updateMotherData(motherIdSet);
    }

    
    private void updateMotherData(List<Child__c> childRecords) {
        Set<Id> motherIdSet = new Set<Id>();
        for(Child__c child : childRecords) {
            if(child.Mother__c != null) {
                motherIdSet.add(child.Mother__c);
            }
        }
        this.updateMotherData(motherIdSet);
    }

    private void updateMotherData(Set<Id> motherIdSet) {
        motherServiceLayer.updateMotherCount(motherIdSet);
    }

    


}