force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Childs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/childObjHandler.cls
public class childObjHandler {
    public childObjHandler() {
        
    }
    public static void updateChilds (List<Child__c> newChildList, Map<Id, Child__c> oldMap) {
        Child__c [] newlistChild = new List<Child__c>();
        for (Child__c chld : newChildList) {
            system.debug('hi');
            if (chld.Age__c != oldMap.get(chld.Id).Age__c && chld.Age__c > 10) {
                newlistChild.add(chld);
                //chld.Name = chld.Name + ' oldeer child';
            }
        }
        
        for (Child__c child : newlistChild) {
            child.Name = child.Name + ' oldest child';
        }
    }
}