force-app/main/default/objects/Record_accessed__e/Record_accessed__e.object-meta.xml
<CustomObject>
    <description>Platform event that is fired by an lwc component when that component is loaded and unloaded
just place this component on the detail page to fire this platform event</description>
    <label>Record accessed</label>
    <pluralLabel>Record accessed</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_accessed__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record id of the opened record</description>
    <label>Record Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_accessed__e/fields/Record_Opened__c.field-meta.xml
<CustomField>
    <fullName>Record_Opened__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When record is access, or else when closed</description>
    <label>Record Opened</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Record_accessed__e/fields/Reply_back__c.field-meta.xml
<CustomField>
    <fullName>Reply_back__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reply back</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Record_accessed__e/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>unique component id generated by component</description>
    <label>UUID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordAccessNotify.cls
public with sharing class RecordAccessNotify {

    @AuraEnabled
    public static void init(Id recordId, String componentId, boolean recordOpened){
        try {
            System.debug('recordid ' + recordId);
            System.debug('componentId ' + componentId);
            publishPlatformEvent(new Record_accessed__e(
                Record_Id__c = recordId,
                Reply_back__c = true,
                UUID__c = componentId,
                Record_Opened__c = recordOpened
            ));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void attendance(Id recordId, String componentId){
        try {
            publishPlatformEvent(new Record_accessed__e(
                Record_Id__c = recordId,
                Reply_back__c = false,
                UUID__c = componentId,
                Record_Opened__c = false
            ));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    private static void publishPlatformEvent(Record_accessed__e platformEvent) {
        publishPlatformEvent(new List<Record_accessed__e>{platformEvent});
    }
    private static void publishPlatformEvent(List<Record_accessed__e> platformEventList) {

        List<Database.SaveResult> results = EventBus.publish(platformEventList);
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) {
                System.debug('Successfully published event.');
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }
    }
}